<?php

function createRelationalSchema(PDO $pdo): void {
    $pdo->exec('CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)');
    $statements = [
        "CREATE TABLE IF NOT EXISTS businesses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            owner_user_id INTEGER NOT NULL UNIQUE,
            tipo TEXT NOT NULL DEFAULT 'moda',
            nome TEXT NOT NULL DEFAULT '',
            responsavel TEXT NOT NULL DEFAULT '',
            tagline TEXT NOT NULL DEFAULT '',
            cnpj TEXT NOT NULL DEFAULT '',
            endereco TEXT NOT NULL DEFAULT '',
            whatsapp TEXT NOT NULL DEFAULT '',
            horario_retirada TEXT NOT NULL DEFAULT '',
            tem_deposito INTEGER NOT NULL DEFAULT 1 CHECK (tem_deposito IN (0, 1)),
            plano TEXT NOT NULL DEFAULT 'profissional',
            criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS store_locations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            nome TEXT NOT NULL,
            endereco TEXT NOT NULL DEFAULT '',
            tipo TEXT NOT NULL DEFAULT 'loja' CHECK (tipo IN ('loja', 'deposito')),
            principal INTEGER NOT NULL DEFAULT 0 CHECK (principal IN (0, 1)),
            ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS suppliers_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            nome TEXT NOT NULL,
            cnpj TEXT NOT NULL DEFAULT '',
            contato_email TEXT NOT NULL DEFAULT '',
            whatsapp TEXT NOT NULL DEFAULT '',
            prazo_dias INTEGER NOT NULL DEFAULT 0 CHECK (prazo_dias >= 0),
            pedido_minimo REAL NOT NULL DEFAULT 0 CHECK (pedido_minimo >= 0),
            ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS products_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            supplier_id INTEGER,
            nome TEXT NOT NULL,
            sku TEXT NOT NULL,
            codigo_barras TEXT NOT NULL DEFAULT '',
            categoria TEXT NOT NULL DEFAULT '',
            descricao TEXT NOT NULL DEFAULT '',
            emoji TEXT NOT NULL DEFAULT '',
            preco REAL NOT NULL DEFAULT 0 CHECK (preco >= 0),
            custo REAL NOT NULL DEFAULT 0 CHECK (custo >= 0),
            estoque_minimo INTEGER NOT NULL DEFAULT 0 CHECK (estoque_minimo >= 0),
            venda_media_dia REAL NOT NULL DEFAULT 0 CHECK (venda_media_dia >= 0),
            prateleira TEXT NOT NULL DEFAULT '',
            capacidade_prateleira INTEGER NOT NULL DEFAULT 0 CHECK (capacidade_prateleira >= 0),
                publicado INTEGER NOT NULL DEFAULT 1 CHECK (publicado IN (0, 1)),
                com_problema INTEGER NOT NULL DEFAULT 0 CHECK (com_problema IN (0, 1)),
                alerta_prateleira INTEGER NOT NULL DEFAULT 0 CHECK (alerta_prateleira IN (0, 1)),
            bloqueio_json TEXT,
            atributos_json TEXT NOT NULL DEFAULT '{}',
            ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
            criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (business_id, legacy_id),
            UNIQUE (business_id, sku),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (supplier_id) REFERENCES suppliers_rel(id) ON DELETE SET NULL
        )",
        "CREATE TABLE IF NOT EXISTS product_variants_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            rotulo TEXT NOT NULL,
            sku TEXT NOT NULL DEFAULT '',
            codigo_barras TEXT NOT NULL DEFAULT '',
            quantidade INTEGER NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
            peso_venda REAL NOT NULL DEFAULT 0 CHECK (peso_venda >= 0),
            atributos_json TEXT NOT NULL DEFAULT '{}',
            UNIQUE (business_id, product_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS sales_channels (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            canal TEXT NOT NULL,
            conectado INTEGER NOT NULL DEFAULT 0 CHECK (conectado IN (0, 1)),
            ajuste_preco REAL NOT NULL DEFAULT 0,
            configuracao_json TEXT NOT NULL DEFAULT '{}',
            UNIQUE (business_id, canal),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS product_channels (
            business_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            channel_id INTEGER NOT NULL,
            publicado INTEGER NOT NULL DEFAULT 0 CHECK (publicado IN (0, 1)),
            PRIMARY KEY (business_id, product_id, channel_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE,
            FOREIGN KEY (channel_id) REFERENCES sales_channels(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS stock_balances (
            business_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            location_id INTEGER NOT NULL,
            quantidade INTEGER NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
            atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (business_id, product_id, location_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE,
            FOREIGN KEY (location_id) REFERENCES store_locations(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS inventory_movements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            variant_id INTEGER,
            location_id INTEGER NOT NULL,
            tipo TEXT NOT NULL,
            quantidade INTEGER NOT NULL,
            referencia_tipo TEXT NOT NULL DEFAULT '',
            referencia_id TEXT NOT NULL DEFAULT '',
            observacao TEXT NOT NULL DEFAULT '',
            ocorrido_em INTEGER NOT NULL,
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE,
            FOREIGN KEY (variant_id) REFERENCES product_variants_rel(id) ON DELETE SET NULL,
            FOREIGN KEY (location_id) REFERENCES store_locations(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS product_lots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            codigo_lote TEXT NOT NULL,
            quantidade INTEGER NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
            vence_em INTEGER NOT NULL,
            UNIQUE (business_id, product_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS product_promotions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            percentual REAL NOT NULL CHECK (percentual > 0 AND percentual <= 100),
            canais_json TEXT NOT NULL DEFAULT '[]',
            inicia_em INTEGER NOT NULL,
            termina_em INTEGER NOT NULL,
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS electronic_labels (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            preco REAL NOT NULL CHECK (preco >= 0),
            percentual_promocao REAL NOT NULL DEFAULT 0,
            desatualizada INTEGER NOT NULL DEFAULT 0 CHECK (desatualizada IN (0, 1)),
            sincronizada_em INTEGER,
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE,
            UNIQUE (business_id, product_id)
        )",
        "CREATE TABLE IF NOT EXISTS orders_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            channel TEXT NOT NULL,
            tipo TEXT NOT NULL,
            cliente_nome TEXT NOT NULL,
            cliente_telefone TEXT NOT NULL DEFAULT '',
            cliente_endereco TEXT NOT NULL DEFAULT '',
            total REAL NOT NULL DEFAULT 0 CHECK (total >= 0),
            frete REAL NOT NULL DEFAULT 0 CHECK (frete >= 0),
            status TEXT NOT NULL,
            metodo_pagamento TEXT NOT NULL DEFAULT '',
            loja_retirada_id INTEGER,
            marketplace_demo TEXT NOT NULL DEFAULT '',
            dados_adicionais_json TEXT NOT NULL DEFAULT '{}',
            ocorrido_em INTEGER NOT NULL,
            atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (loja_retirada_id) REFERENCES store_locations(id) ON DELETE SET NULL
        )",
        "CREATE TABLE IF NOT EXISTS order_items_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            order_id INTEGER NOT NULL,
            product_id INTEGER,
            variant_id INTEGER,
            location_id INTEGER,
            sku_snapshot TEXT NOT NULL DEFAULT '',
            nome_snapshot TEXT NOT NULL,
            quantidade INTEGER NOT NULL CHECK (quantidade > 0),
            preco_unitario REAL NOT NULL CHECK (preco_unitario >= 0),
            bipado INTEGER NOT NULL DEFAULT 0 CHECK (bipado IN (0, 1)),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (order_id) REFERENCES orders_rel(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE SET NULL,
            FOREIGN KEY (variant_id) REFERENCES product_variants_rel(id) ON DELETE SET NULL,
            FOREIGN KEY (location_id) REFERENCES store_locations(id) ON DELETE SET NULL
        )",
        "CREATE TABLE IF NOT EXISTS order_returns (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            order_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            tipo TEXT NOT NULL,
            motivo TEXT NOT NULL DEFAULT '',
            valor REAL NOT NULL DEFAULT 0 CHECK (valor >= 0),
            credito_codigo TEXT NOT NULL DEFAULT '',
            ocorrido_em INTEGER NOT NULL,
            UNIQUE (business_id, order_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (order_id) REFERENCES orders_rel(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS order_return_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            return_id INTEGER NOT NULL,
            order_item_index INTEGER NOT NULL DEFAULT 0,
            product_id INTEGER,
            variant_id INTEGER,
            quantidade INTEGER NOT NULL CHECK (quantidade > 0),
            valor_unitario REAL NOT NULL DEFAULT 0 CHECK (valor_unitario >= 0),
            voltou_estoque INTEGER NOT NULL DEFAULT 0 CHECK (voltou_estoque IN (0, 1)),
            custo_total REAL NOT NULL DEFAULT 0 CHECK (custo_total >= 0),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (return_id) REFERENCES order_returns(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE SET NULL,
            FOREIGN KEY (variant_id) REFERENCES product_variants_rel(id) ON DELETE SET NULL
        )",
        "CREATE TABLE IF NOT EXISTS stock_reservations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            order_item_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            variant_id INTEGER,
            location_id INTEGER,
            quantidade INTEGER NOT NULL CHECK (quantidade > 0),
            status TEXT NOT NULL,
            criado_em INTEGER NOT NULL,
            UNIQUE (business_id, order_item_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (order_item_id) REFERENCES order_items_rel(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE CASCADE,
            FOREIGN KEY (variant_id) REFERENCES product_variants_rel(id) ON DELETE SET NULL,
            FOREIGN KEY (location_id) REFERENCES store_locations(id) ON DELETE SET NULL
        )",
        "CREATE TABLE IF NOT EXISTS purchase_orders_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            supplier_id INTEGER,
            status TEXT NOT NULL,
            origem_automacao INTEGER NOT NULL DEFAULT 0 CHECK (origem_automacao IN (0, 1)),
            motivo TEXT NOT NULL DEFAULT '',
            criado_em INTEGER NOT NULL,
            enviado_em INTEGER,
            previsao_entrega_em INTEGER,
            atributos_json TEXT NOT NULL DEFAULT '{}',
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (supplier_id) REFERENCES suppliers_rel(id) ON DELETE SET NULL
        )",
        "CREATE TABLE IF NOT EXISTS purchase_order_items_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            purchase_order_id INTEGER NOT NULL,
            product_id INTEGER,
            sku_snapshot TEXT NOT NULL DEFAULT '',
            nome_snapshot TEXT NOT NULL,
            quantidade INTEGER NOT NULL CHECK (quantidade > 0),
            recebida INTEGER NOT NULL DEFAULT 0 CHECK (recebida >= 0),
            custo_unitario REAL NOT NULL DEFAULT 0 CHECK (custo_unitario >= 0),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders_rel(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE SET NULL
        )",
        "CREATE TABLE IF NOT EXISTS expenses_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            categoria TEXT NOT NULL,
            descricao TEXT NOT NULL,
            valor REAL NOT NULL CHECK (valor >= 0),
            data_texto TEXT NOT NULL DEFAULT '',
            ocorrido_em INTEGER,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS invoices_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            order_legacy_id TEXT NOT NULL DEFAULT '',
            channel TEXT NOT NULL DEFAULT '',
            chave TEXT NOT NULL DEFAULT '',
            total REAL NOT NULL DEFAULT 0 CHECK (total >= 0),
            emitida_em INTEGER,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS invoice_items_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            invoice_id INTEGER NOT NULL,
            sku_snapshot TEXT NOT NULL DEFAULT '',
            nome_snapshot TEXT NOT NULL,
            quantidade INTEGER NOT NULL CHECK (quantidade > 0),
            preco_unitario REAL NOT NULL CHECK (preco_unitario >= 0),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (invoice_id) REFERENCES invoices_rel(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS shipping_labels_rel (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            order_legacy_id TEXT NOT NULL DEFAULT '',
            channel TEXT NOT NULL DEFAULT '',
            codigo_rastreio TEXT NOT NULL DEFAULT '',
            destinatario TEXT NOT NULL DEFAULT '',
            peso REAL NOT NULL DEFAULT 0 CHECK (peso >= 0),
            criado_em INTEGER,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS customer_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            order_legacy_id TEXT NOT NULL DEFAULT '',
            destinatario TEXT NOT NULL DEFAULT '',
            telefone TEXT NOT NULL DEFAULT '',
            mensagem TEXT NOT NULL,
            enviado_em INTEGER,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS business_notifications (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            tipo TEXT NOT NULL,
            mensagem TEXT NOT NULL,
            rota TEXT NOT NULL DEFAULT '',
            lida INTEGER NOT NULL DEFAULT 0 CHECK (lida IN (0, 1)),
            criado_em INTEGER,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS automation_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            regra TEXT NOT NULL,
            mensagem TEXT NOT NULL,
            criado_em INTEGER,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS inventory_scans (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            tipo TEXT NOT NULL,
            sku TEXT NOT NULL DEFAULT '',
            produto TEXT NOT NULL DEFAULT '',
            local TEXT NOT NULL DEFAULT '',
            lido_em INTEGER,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS inventory_losses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            product_id INTEGER,
            motivo TEXT NOT NULL DEFAULT '',
            quantidade INTEGER NOT NULL DEFAULT 0,
            valor REAL NOT NULL DEFAULT 0 CHECK (valor >= 0),
            ocorrido_em INTEGER,
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
            FOREIGN KEY (product_id) REFERENCES products_rel(id) ON DELETE SET NULL,
            UNIQUE (business_id, legacy_id)
        )",
        "CREATE TABLE IF NOT EXISTS store_credits (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            codigo TEXT NOT NULL,
            cliente TEXT NOT NULL DEFAULT '',
            order_legacy_id TEXT NOT NULL DEFAULT '',
            valor_inicial REAL NOT NULL CHECK (valor_inicial >= 0),
            saldo REAL NOT NULL CHECK (saldo >= 0),
            criado_em INTEGER,
            UNIQUE (business_id, codigo),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS seasonal_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            nome TEXT NOT NULL,
            data_evento TEXT NOT NULL DEFAULT '',
            multiplicador REAL NOT NULL DEFAULT 1,
            dias_janela INTEGER NOT NULL DEFAULT 1,
            atributos_json TEXT NOT NULL DEFAULT '{}',
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS seasonal_reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            business_id INTEGER NOT NULL,
            legacy_id TEXT NOT NULL,
            nome TEXT NOT NULL,
            dados_json TEXT NOT NULL,
            UNIQUE (business_id, legacy_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS business_preferences (
            business_id INTEGER NOT NULL,
            chave TEXT NOT NULL,
            valor TEXT NOT NULL,
            tipo_valor TEXT NOT NULL DEFAULT 'string',
            atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (business_id, chave),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        "CREATE TABLE IF NOT EXISTS relational_sync_state (
            business_id INTEGER NOT NULL,
            origem TEXT NOT NULL,
            revision INTEGER NOT NULL,
            atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (business_id, origem),
            FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
        )",
        'CREATE INDEX IF NOT EXISTS idx_products_business_active ON products_rel (business_id, ativo, nome)',
        'CREATE INDEX IF NOT EXISTS idx_orders_business_time ON orders_rel (business_id, ocorrido_em DESC)',
        'CREATE INDEX IF NOT EXISTS idx_orders_business_channel_status ON orders_rel (business_id, channel, status)',
        'CREATE INDEX IF NOT EXISTS idx_stock_movements_business_time ON inventory_movements (business_id, ocorrido_em DESC)',
        'CREATE INDEX IF NOT EXISTS idx_reservations_business_status ON stock_reservations (business_id, status)',
        'CREATE INDEX IF NOT EXISTS idx_notifications_business_time ON business_notifications (business_id, criado_em DESC)',
    ];

    foreach ($statements as $statement) {
        $pdo->exec($statement);
    }
    $pdo->exec('INSERT OR IGNORE INTO schema_migrations (version) VALUES (1)');

    // Versão 2: ficha completa do fornecedor (endereço, telefone, responsável, observações...)
    $supplierColumns = array_column($pdo->query('PRAGMA table_info(suppliers_rel)')->fetchAll(PDO::FETCH_ASSOC), 'name');
    if (!in_array('atributos_json', $supplierColumns, true)) {
        $pdo->exec("ALTER TABLE suppliers_rel ADD COLUMN atributos_json TEXT NOT NULL DEFAULT '{}'");
    }
    $pdo->exec('INSERT OR IGNORE INTO schema_migrations (version) VALUES (2)');

    // Versão 3 (área do consultor) depende de users e leads, criadas em schema.php
    $baseTables = $pdo->query("SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name IN ('users', 'leads')")->fetchColumn();
    if ((int)$baseTables === 2 && function_exists('createConsultorSchema')) {
        createConsultorSchema($pdo);
    }
}
